# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_bms', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('A', 'Art'), ('F', 'Food'), ('M', 'Music'), ('S', 'Shopping'), ('T', 'Theatre')], default='Null', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='event_paid',
            field=models.CharField(choices=[('P', 'Paid'), ('F', 'Free')], default='Null', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='event_venue',
            field=models.CharField(default='No', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paidevent',
            name='bms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yellow_line.Event'),
        ),
    ]
