# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0002_auto_20161204_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidevent',
            name='event_bms',
        ),
    ]
