# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0003_remove_paidevent_event_bms'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidevent',
            name='event_bms',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
