# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 18:57
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0004_paidevent_event_bms'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_position',
            field=geoposition.fields.GeopositionField(default='Null', max_length=42),
            preserve_default=False,
        ),
    ]
