# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0005_event_event_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_venue', models.CharField(max_length=200)),
                ('event_position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_position',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_venue',
        ),
        migrations.AddField(
            model_name='event',
            name='event_metro',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
