# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0006_auto_20161206_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='venue',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='yellow_line.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='event_venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
