# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0007_auto_20161206_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='event_venue',
        ),
        migrations.AddField(
            model_name='event',
            name='event_venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
