# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0008_auto_20161206_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidevent',
            name='event_bms',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
