# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellow_line', '0009_auto_20161206_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidevent',
            name='event_bms',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
    ]
